name: Release and Publish @realtimemd/react-time-picker

on:
  workflow_dispatch:
    inputs:
      semverStrategy:
        description: 'Select semantic version bump strategy'
        type: choice
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
          - decline

env:
  HUSKY: 0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.10.0
          registry-url: https://npm.pkg.github.com/

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Bump package version
        run: yarn workspace @realtimemd/react-time-picker version "${{ github.event.inputs.semverStrategy }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read bumped version
        id: read_version
        run: |
          node -e '
            const fs = require("fs");
            const pkg = JSON.parse(fs.readFileSync("packages/react-time-picker/package.json", "utf8"));
            const v = pkg.version;
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `version=${v}\n`);
            fs.appendFileSync(process.env.GITHUB_ENV, `NEW_VERSION=${v}\n`);
            console.log(`Detected version: ${v}`);
          '

      - name: Commit Updated package.json file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Package.json to ${{ steps.read_version.outputs.version }}"
          git push

      - name: Publish
        run: yarn npm publish
        working-directory: packages/react-time-picker
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          name: Release ${{ steps.read_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
