name: Release and Publish @realtimemd/react-time-picker

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'New Semantic Release Version No.'
        default: ''
        required: true
        type: string

env:
  HUSKY: 0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.10.0
          registry-url: https://npm.pkg.github.com/

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Bump package version
        run: yarn version --new-version "${{ github.event.inputs.newversion }}" --no-git-tag-version
        working-directory: packages/react-time-picker
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Commit Updated package.json file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Package.json to ${{ github.event.inputs.newversion }}"
          git push

      - name: Publish
        run: yarn npm publish
        working-directory: packages/react-time-picker
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PACKAGE_DEPLOY_RELEASE }} # This token is provided by Actions, you do not need to create your own token
          tag_name: v${{ github.event.inputs.newversion }}
          name: Release ${{ github.event.inputs.newversion }}
          draft: false
          prerelease: false
